version: '2'
services:

  redis:
    image: redis

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

